permalink: /:year:month:day/:title
url: http://chartjunk.art
baseurl: /project

# variables
name: Chart Junk
description: Throw out the Charjunk Trash
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true